### PR TITLE
Agents that supply script with their HTML content are now rendered in sandboxed Iframes

### PR DESCRIPTION
**Pull request by robgruen**
FYI @curtisman

### CODE REVIEW

**Comment by curtisman** [comment]
Great! Thank you for doing.   

One small change to the API: instead of asking for script to be added, we can change the API for iframe/non-iframe HTML, and just allow non-purified HTML into the iframe?

**Comment by robgruen** [comment]
Good idea, I like it!!!  I'll make that change.

________________________________

**Comment by robgruen** [comment]
> Great! Thank you for doing this!
> 
> One small change to the API: instead of asking for script to be added, we can change the API for iframe/non-iframe HTML, and just allow non-purified HTML into the iframe? Do you see any potential problems with that?

As for potential problems....I'm sure we'll find out at some point but it does seem reasonable thing to allow.  We can put affordances in the settings or something so people can either turn that functionality on or off so if you're in a spot where you have untrusted agents you can just turn that functionality off.  I'll make a work item for that.

**Comment by robgruen** [comment]
> > Great! Thank you for doing this!
> > One small change to the API: instead of asking for script to be added, we can change the API for iframe/non-iframe HTML, and just allow non-purified HTML into the iframe? Do you see any potential problems with that?
> 
> As for potential problems....I'm sure we'll find out at some point but it does seem reasonable thing to allow. We can put affordances in the settings or something so people can either turn that functionality on or off so if you're in a spot where you have untrusted agents you can just turn that functionality off. I'll make a work item for that.

...I've completed this work but have NOT surfaced the setting in the UI.

**Pull request merged**
